"""Step definitions for the Medication Reminders and Scheduling feature.

Tests the daily schedule generation from the database layer, verifying
that medications appear correctly and completion status is tracked.

Architecture:
  - Tests hit MedMinderDB.get_todays_schedule() directly.
  - Schedule entries are dicts with medication_name, dosage, scheduled_times,
    doses_logged_today, and all_taken fields.
  - No external API keys or services required.

⚕️ MEDICAL DISCLAIMER:
  These tests validate software behaviour only. Medication schedules
  generated by this system should NOT be relied upon as the sole
  reminder mechanism for critical medications.
"""

from __future__ import annotations

import pytest
from pytest_bdd import given, parsers, scenario, then, when


# ---------------------------------------------------------------------------
# Feature file path
# ---------------------------------------------------------------------------
FEATURE_FILE = "../features/medication_reminders.feature"


# ---------------------------------------------------------------------------
# Scenario Declarations
# ---------------------------------------------------------------------------

@scenario(FEATURE_FILE, "View empty schedule")
def test_view_empty_schedule():
    """Verify that an empty schedule is returned when no medications exist."""
    pass


@scenario(FEATURE_FILE, "View schedule with medications")
def test_view_schedule_with_medications():
    """Verify that the schedule lists all active medications."""
    pass


@scenario(FEATURE_FILE, "Schedule shows completion status")
def test_schedule_shows_completion_status():
    """Verify that the schedule reflects logged doses."""
    pass


# ---------------------------------------------------------------------------
# Background Steps
# ---------------------------------------------------------------------------

@given("the MedMinder database is initialized", target_fixture="db")
def db_is_initialized(test_db):
    """Provide the initialised test database to all steps."""
    return test_db


@given(
    parsers.parse('user "{user_name}" exists in the system'),
    target_fixture="user_id",
)
def user_exists(db, user_name, event_loop):
    """Ensure the test user exists in the database.

    Returns:
        The user_id string.
    """
    user = event_loop.run_until_complete(
        db.get_or_create_user(user_name, user_name)
    )
    return user.id


# ---------------------------------------------------------------------------
# Given Steps — Pre-populate Data
# ---------------------------------------------------------------------------
# We store created medications in a dict keyed by name so multiple
# Given steps can reference them (e.g., to log doses for them later).
# ---------------------------------------------------------------------------

@given(
    parsers.parse(
        'the user has medication "{med_name}" with dosage "{dosage}" '
        'frequency "{frequency}" at times "{times}"'
    ),
    target_fixture="existing_medication",
)
def user_has_medication(db, user_id, med_name, dosage, frequency, times, event_loop, request):
    """Add a medication to the test database.

    We also store it in a medications_map on the test's node so
    that subsequent Given steps (like logging doses) can look it up
    by name.

    Returns:
        The created Medication model instance.
    """
    times_list = [t.strip() for t in times.split(",")]
    medication = event_loop.run_until_complete(
        db.add_medication(
            user_id=user_id,
            name=med_name,
            dosage=dosage,
            frequency=frequency,
            times=times_list,
        )
    )

    # Store in a shared dict on the pytest node for cross-step access
    if not hasattr(request, "medications_map"):
        request.medications_map = {}
    request.medications_map[med_name] = medication

    return medication


@given(
    parsers.parse('the user has logged a "{status}" dose for "{med_name}"'),
    target_fixture="logged_dose",
)
def user_has_logged_dose(db, user_id, status, med_name, existing_medication, event_loop):
    """Log a dose for an existing medication.

    Uses the `existing_medication` fixture to get the medication ID.
    This step is used in Background or Given clauses where dose data
    needs to be pre-populated before the When step.

    Returns:
        The created DoseLog model instance.
    """
    dose = event_loop.run_until_complete(
        db.log_dose(
            medication_id=existing_medication.id,
            status=status,
        )
    )
    return dose


# ---------------------------------------------------------------------------
# When Steps
# ---------------------------------------------------------------------------

@when("the user requests today's schedule", target_fixture="schedule")
def request_todays_schedule(db, user_id, event_loop):
    """Request today's medication schedule from the database.

    Returns:
        A list of schedule dicts, one per active medication.
    """
    schedule = event_loop.run_until_complete(
        db.get_todays_schedule(user_id)
    )
    return schedule


# ---------------------------------------------------------------------------
# Then Steps
# ---------------------------------------------------------------------------

@then("the schedule should be empty")
def schedule_is_empty(schedule):
    """Assert that the schedule contains no medications."""
    assert len(schedule) == 0, (
        f"Expected empty schedule, but found {len(schedule)} entries"
    )


@then(parsers.parse("the schedule should contain {count:d} medications"))
def schedule_contains_count(schedule, count):
    """Assert that the schedule has the expected number of medications.

    Args:
        schedule: The schedule list from the When step.
        count: Expected number of medication entries.
    """
    assert len(schedule) == count, (
        f"Expected {count} medications in schedule, "
        f"but found {len(schedule)}: "
        f"{[s['medication_name'] for s in schedule]}"
    )


@then(parsers.parse('the schedule should include "{med_name}"'))
def schedule_includes_medication(schedule, med_name):
    """Assert that the named medication appears in the schedule."""
    med_names = [s["medication_name"] for s in schedule]
    assert med_name in med_names, (
        f"Expected '{med_name}' in schedule, "
        f"but found: {med_names}"
    )


@then(parsers.parse('the schedule should show doses logged for "{med_name}"'))
def schedule_shows_doses_logged(schedule, med_name):
    """Assert that the schedule shows at least one dose logged for the medication.

    Checks the `doses_logged_today` field in the schedule entry
    for the named medication.
    """
    # Find the schedule entry for this medication
    entry = None
    for s in schedule:
        if s["medication_name"] == med_name:
            entry = s
            break

    assert entry is not None, (
        f"Medication '{med_name}' not found in schedule"
    )
    assert entry["doses_logged_today"] > 0, (
        f"Expected doses_logged_today > 0 for '{med_name}', "
        f"but got {entry['doses_logged_today']}"
    )
